### ISSUE TITLE
账户直接虚无，重置密码后无法更改密码；在使用Adguard的时候有机率无法登入

### ISSUE THREAD

**Issue by ous50** [tmplink/TMP_tmpUI#27]
emmmm有一段时间没看钛盘然后现在发现账户无法登入，重置了密码后发现是adguard拦截的问题（有injection的域名报错）
关闭adg后登录再清除所有数据并开启adg再试就玄学变好，且无法更改密码, return "Modification failed, please log in again" 。以上是23号的发现。
今天再看的时候，就发现我所有在里面存的东西都没有了。找到以前文件的link点进去也会提示file is no longer available...连补档都无法妙传。无法更改密码, return "Modification failed, please log in again" 的问题依然存在。

**Comment by tmplink** [comment]
请问这个问题目前还存在吗？

**Comment by ous50** [comment]
现在已经没有再发生过这种事情了。
