### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by hong-tm** [tmplink/TMP_tmpUI#97]
### 电脑网页端无法上传文件，上传始终没动
![Snipaste_2022-03-24_13-39-40](https://user-images.githubusercontent.com/51999870/159850176-a2b2e0bd-41be-4f7c-8364-16bbebddd5ec.png)

**Comment by tmplink** [comment]
目前没有复现此问题，可能不是大规模的问题。
请在上传前打开开发人员工具监控网络选项卡，上传发生此错误时，查看一下网络部分的报错信息。

**Comment by hong-tm** [comment]
# 前
![Snipaste_2022-03-24_21-24-09](https://user-images.githubusercontent.com/51999870/159925680-9380e492-4a64-4243-b9ff-41aca9fa93b9.png)
# 后
![Snipaste_2022-03-24_21-24-24](https://user-images.githubusercontent.com/51999870/159925668-bda69a7a-0271-4096-9cd5-7b2cadce4e08.png)

**Comment by tmplink** [comment]
请在网络选项卡打开“ domain” 选项后再记录一次。
需要这项信息进行判断。

**Comment by hong-tm** [comment]
> 请在网络选项卡打开“ domain” 选项后再记录一次。 需要这项信息进行判断。

Domain? 是哪个选项我不是很清楚，不好意思？

**Comment by tmplink** [comment]
英文应该是叫 domain，中文界面是叫“域”。
或者点进变红的两个请求，看一下请求的具体地址。

**Comment by tmplink** [comment]
马来西亚吗？马来西亚应该不会受到影响（服务器在欧洲）。
请尝试 ping 一下调查中的那个域名。看看网络是否正常。

**Comment by hong-tm** [comment]
> 马来西亚吗？马来西亚应该不会受到影响（服务器在欧洲）。 请尝试 ping 一下调查中的那个域名。看看网络是否正常。

话说我是开vpn不是开代理，代理不是很会弄

**Comment by tmplink** [comment]
原来是因为校园网。部分校园网可能会有端口限制，我们的存储服务使用的不是标准端口(616)。

ps.广告一下我们面向海外用户提供的服务 https://www.vnet.one

**Comment by hong-tm** [comment]
> 

ok 我去看看

**Comment by tmplink** [comment]
> 我试了不开代理不行，应该是我这边的校园网有白名单，蛮多网站都进不去要代理

目前我们已经针对存储网络做出了调整，现在开始使用标准端口来提供服务，因此这可以广泛兼容于各种安全限制比较强的公共网络，比如校园网。
